[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { version = "21.6.0", default-features = false }

[dev-dependencies]
soroban-sdk = { version = "21.6.0", features = ["testutils"] }